# Generated by Django 5.0.4 on 2024-05-12 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Наименование')),
                ('residence', models.CharField(default='', max_length=100, verbose_name='Резидент')),
                ('vat', models.CharField(default='', max_length=100, verbose_name='Регистрационный номер')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='Электронная почта')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Телефон')),
                ('country', models.CharField(default='', max_length=100, verbose_name='Страна')),
                ('postcode', models.CharField(default='', max_length=20, verbose_name='Индекс')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Город')),
                ('street_name', models.CharField(default='', max_length=200, verbose_name='Улица')),
                ('house_number', models.CharField(default='', max_length=20, verbose_name='Дом')),
                ('industry', models.CharField(default='', max_length=200, verbose_name='Вид деятельности')),
                ('primary_role', models.CharField(default='', max_length=100, verbose_name='Роль')),
                ('secondary_role', models.CharField(default='', max_length=100, verbose_name='Доп. роль')),
                ('status', models.CharField(default='', max_length=100, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
