# Generated by Django 5.0.4 on 2024-05-12 19:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_partner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('title', models.CharField(blank=True, choices=[('Менеджер', 'Менеджер'), ('Директор', 'Директор'), ('Представитель', 'Представитель'), ('Другой', 'Другой')], max_length=50, null=True, verbose_name='Должность')),
                ('department', models.CharField(blank=True, choices=[('Продажи', 'Продажи'), ('Маркетинг', 'Маркетинг'), ('IT', 'IT'), ('Финансы', 'Финансы'), ('HR', 'HR'), ('Другое', 'Другое')], max_length=50, null=True, verbose_name='Отдел')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('last_contacted', models.DateField(default=datetime.date.today, verbose_name='Последнее взаимодействие')),
                ('preferred_communication', models.CharField(blank=True, choices=[('Электронная почта', 'Электронная почта'), ('Телефон', 'Телефон'), ('Текст', 'Текст'), ('Лично', 'Лично')], max_length=50, null=True, verbose_name='Предпочтительный способ связи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('business_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='business_partner.businesspartner', verbose_name='Контрагент')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
